module Spine
  module Countries
    autoload :Country, 'spine/countries/country'
    autoload :Registry, 'spine/countries/registry'

    extend Registry

    define 'AD', name: 'Andorra'
    define 'AE', name: 'United Arab Emirates'
    define 'AF', name: 'Afganistan'
    define 'AG', name: 'Antigua and Barbuda'
    define 'AI', name: 'Anguilla'
    define 'AL', name: 'Albania'
    define 'AM', name: 'Armenia'
    define 'AO', name: 'Angola'
    define 'AQ', name: 'Antarctica'
    define 'AR', name: 'Argentina'
    define 'AS', name: 'American Samoa'
    define 'AT', name: 'Austria'
    define 'AU', name: 'Australia'
    define 'AW', name: 'Aruba'
    define 'AX', name: 'Åland Islands'
    define 'AZ', name: 'Azerbaijan'
    define 'BA', name: 'Bosnia and Herzegovina'
    define 'BB', name: 'Barbados'
    define 'BD', name: 'Bangladesh'
    define 'BE', name: 'Belgium'
    define 'BF', name: 'Burkina Faso'
    define 'BG', name: 'Bulgaria'
    define 'BH', name: 'Bahrain'
    define 'BI', name: 'Burundi'
    define 'BJ', name: 'Benin'
    define 'BL', name: 'Saint Barthélemy'
    define 'BM', name: 'Bermuda'
    define 'BN', name: 'Brunei Darussalam'
    define 'BO', name: 'Bolivia, Plurinational State of'
    define 'BQ', name: 'Bonaire, Sint Eustatius and Saba'
    define 'BR', name: 'Brazil'
    define 'BS', name: 'Bahamas'
    define 'BT', name: 'Bhutan'
    define 'BV', name: 'Bouvet Island'
    define 'BW', name: 'Botswana'
    define 'BY', name: 'Belarus'
    define 'BZ', name: 'Belize'
    define 'CA', name: 'Canada'
    define 'CC', name: 'Cocos (Keeling) Islands'
    define 'CD', name: 'Congo, the Democratic Republic of the'
    define 'CF', name: 'Central African Republic'
    define 'CG', name: 'Congo'
    define 'CH', name: 'Switzerland'
    define 'CI', name: "Côte d'Ivoire"
    define 'CK', name: 'Cook Islands'
    define 'CL', name: 'Chile'
    define 'CM', name: 'Cameroon'
    define 'CN', name: 'China'
    define 'CO', name: 'Colombia'
    define 'CR', name: 'Costa Rica'
    define 'CU', name: 'Cuba'
    define 'CV', name: 'Cabo Verde'
    define 'CW', name: 'Curaçao'
    define 'CX', name: 'Christmas Island'
    define 'CY', name: 'Cyprus'
    define 'CZ', name: 'Czech Republic'
    define 'DE', name: 'Germany'
    define 'DJ', name: 'Djibouti'
    define 'DK', name: 'Denmark'
    define 'DM', name: 'Dominica'
    define 'DO', name: 'Dominican Republic'
    define 'DZ', name: 'Algeria'
    define 'EC', name: 'Ecuador'
    define 'EE', name: 'Estonia'
    define 'EG', name: 'Egypt'
    define 'EH', name: 'Western Sahara'
    define 'ER', name: 'Eritrea'
    define 'ES', name: 'Spain'
    define 'ET', name: 'Ethiopia'
    define 'FI', name: 'Finland'
    define 'FJ', name: 'Fiji'
    define 'FK', name: 'Falkland Islands (Malvinas)'
    define 'FM', name: 'Micronesia, Federated States of'
    define 'FO', name: 'Faroe Islands'
    define 'FR', name: 'France'
    define 'GA', name: 'Gabon'
    define 'GB', name: 'United Kingdom'
    define 'GD', name: 'Grenada'
    define 'GE', name: 'Georgia'
    define 'GF', name: 'French Guiana'
    define 'GG', name: 'Guernsey'
    define 'GH', name: 'Ghana'
    define 'GI', name: 'Gibraltar'
    define 'GL', name: 'Greenland'
    define 'GM', name: 'Gambia'
    define 'GN', name: 'Guinea'
    define 'GP', name: 'Guadeloupe'
    define 'GQ', name: 'Equatorial Guinea'
    define 'GR', name: 'Greece'
    define 'GS', name: 'South Georgia and the South Sandwich Islands'
    define 'GT', name: 'Guatemala'
    define 'GU', name: 'Guam'
    define 'GW', name: 'Guinea-Bissau'
    define 'GY', name: 'Guyana'
    define 'HK', name: 'Hong Kong'
    define 'HM', name: 'Heard Island and McDonald Islands'
    define 'HN', name: 'Honduras'
    define 'HR', name: 'Croatia'
    define 'HT', name: 'Haiti'
    define 'HU', name: 'Hungary'
    define 'ID', name: 'Indonesia'
    define 'IE', name: 'Ireland'
    define 'IL', name: 'Israel'
    define 'IM', name: 'Isle of Man'
    define 'IN', name: 'India'
    define 'IO', name: 'British Indian Ocean Territory'
    define 'IQ', name: 'Iraq'
    define 'IR', name: 'Iran, Islamic Republic of'
    define 'IS', name: 'Iceland'
    define 'IT', name: 'Italy'
    define 'JE', name: 'Jersey'
    define 'JM', name: 'Jamaica'
    define 'JO', name: 'Jordan'
    define 'JP', name: 'Japan'
    define 'KE', name: 'Kenya'
    define 'KG', name: 'Kyrgyzstan'
    define 'KH', name: 'Cambodia'
    define 'KI', name: 'Kiribati'
    define 'KM', name: 'Comoros'
    define 'KN', name: 'Saint Kitts and Nevis'
    define 'KP', name: "Korea, Democratic People's Republic of"
    define 'KR', name: 'Korea, Republic of'
    define 'KW', name: 'Kuwait'
    define 'KY', name: 'Cayman Islands'
    define 'KZ', name: 'Kazakhstan'
    define 'LA', name: "Lao People's Democratic Republic"
    define 'LB', name: 'Lebanon'
    define 'LC', name: 'Saint Lucia'
    define 'LI', name: 'Liechtenstein'
    define 'LK', name: 'Sri Lanka'
    define 'LR', name: 'Liberia'
    define 'LS', name: 'Lesotho'
    define 'LT', name: 'Lithuania'
    define 'LU', name: 'Luxembourg'
    define 'LV', name: 'Latvia'
    define 'LY', name: 'Libya'
    define 'MA', name: 'Morocco'
    define 'MC', name: 'Monaco'
    define 'MD', name: 'Moldova, Republic of'
    define 'ME', name: 'Montenegro'
    define 'MF', name: 'Saint Martin (French part)'
    define 'MG', name: 'Madagascar'
    define 'MH', name: 'Marshall Islands'
    define 'MK', name: 'Macedonia, the former Yugoslav Republic of'
    define 'ML', name: 'Mali'
    define 'MM', name: 'Myanmar'
    define 'MN', name: 'Mongolia'
    define 'MO', name: 'Macao'
    define 'MP', name: 'Northern Mariana Islands'
    define 'MQ', name: 'Martinique'
    define 'MR', name: 'Mauritania'
    define 'MS', name: 'Montserrat'
    define 'MT', name: 'Malta'
    define 'MU', name: 'Mauritius'
    define 'MV', name: 'Maldives'
    define 'MW', name: 'Malawi'
    define 'MX', name: 'Mexico'
    define 'MY', name: 'Malaysia'
    define 'MZ', name: 'Mozambique'
    define 'NA', name: 'Namibia'
    define 'NC', name: 'New Caledonia'
    define 'NE', name: 'Niger'
    define 'NF', name: 'Norfolk Island'
    define 'NG', name: 'Nigeria'
    define 'NI', name: 'Nicaragua'
    define 'NL', name: 'Netherlands'
    define 'NO', name: 'Norway'
    define 'NP', name: 'Nepal'
    define 'NR', name: 'Nauru'
    define 'NU', name: 'Niue'
    define 'NZ', name: 'New Zealand'
    define 'OM', name: 'Oman'
    define 'PA', name: 'Panama'
    define 'PE', name: 'Peru'
    define 'PF', name: 'French Polynesia'
    define 'PG', name: 'Papua New Guinea'
    define 'PH', name: 'Philippines'
    define 'PK', name: 'Pakistan'
    define 'PL', name: 'Poland'
    define 'PM', name: 'Saint Pierre and Miquelon'
    define 'PN', name: 'Pitcairn'
    define 'PR', name: 'Puerto Rico'
    define 'PS', name: 'Palestine, State of'
    define 'PT', name: 'Portugal'
    define 'PW', name: 'Palau'
    define 'PY', name: 'Paraguay'
    define 'QA', name: 'Qatar'
    define 'RE', name: 'Réunion'
    define 'RO', name: 'Romania'
    define 'RS', name: 'Serbia'
    define 'RU', name: 'Russian Federation'
    define 'RW', name: 'Rwanda'
    define 'SA', name: 'Saudi Arabia'
    define 'SB', name: 'Solomon Islands'
    define 'SC', name: 'Seychelles'
    define 'SD', name: 'Sudan'
    define 'SE', name: 'Sweden'
    define 'SG', name: 'Singapore'
    define 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha'
    define 'SI', name: 'Slovenia'
    define 'SJ', name: 'Svalbard and Jan Mayen'
    define 'SK', name: 'Slovakia'
    define 'SL', name: 'Sierra Leone'
    define 'SM', name: 'San Marino'
    define 'SN', name: 'Senegal'
    define 'SO', name: 'Somalia'
    define 'SR', name: 'Suriname'
    define 'SS', name: 'South Sudan'
    define 'ST', name: 'Sao Tome and Principe'
    define 'SV', name: 'El Salvador'
    define 'SX', name: 'Sint Maarten (Dutch part)'
    define 'SY', name: 'Syrian Arab Republic'
    define 'SZ', name: 'Swaziland'
    define 'TC', name: 'Turks and Caicos Islands'
    define 'TD', name: 'Chad'
    define 'TF', name: 'French Southern Territories'
    define 'TG', name: 'Togo'
    define 'TH', name: 'Thailand'
    define 'TJ', name: 'Tajikistan'
    define 'TK', name: 'Tokelau'
    define 'TL', name: 'Timor-Leste'
    define 'TM', name: 'Turkmenistan'
    define 'TN', name: 'Tunisia'
    define 'TO', name: 'Tonga'
    define 'TR', name: 'Turkey'
    define 'TT', name: 'Trinidad and Tobago'
    define 'TV', name: 'Tuvalu'
    define 'TW', name: 'Taiwan, Province of China'
    define 'TZ', name: 'Tanzania, United Republic of'
    define 'UA', name: 'Ukraine'
    define 'UG', name: 'Uganda'
    define 'UM', name: 'United States Minor Outlying Islands'
    define 'US', name: 'United States'
    define 'UY', name: 'Uruguay'
    define 'UZ', name: 'Uzbekistan'
    define 'VA', name: 'Holy See (Vatican City State)'
    define 'VC', name: 'Saint Vincent and the Grenadines'
    define 'VE', name: 'Venezuela, Bolivarian Republic of'
    define 'VG', name: 'Virgin Islands, British'
    define 'VI', name: 'Virgin Islands, U.S.'
    define 'VN', name: 'Viet Nam'
    define 'VU', name: 'Vanuatu'
    define 'WF', name: 'Wallis and Futuna'
    define 'WS', name: 'Samoa'
    define 'YE', name: 'Yemen'
    define 'YT', name: 'Mayotte'
    define 'ZA', name: 'South Africa'
    define 'ZM', name: 'Zambia'
    define 'ZW', name: 'Zimbabwe'
  end
end
